# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

# Launch services
exec-once = swaync
exec-once = waybar
exec-once = hyprpaper

# Stuff for cliphist
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Startup initial apps
exec-once = [workspace special:specialbtop silent] $terminal --app-id=specialbtop -e btop

exec-once = [workspace 1] discord
exec-once = [workspace 1] spotify-launcher

exec-once = [workspace 2] firefox
