# See https://wiki.hyprland.org/Configuring/Keywords/

# Sets "Windows" key as main modifier
$mainMod = SUPER

# Set programs that you use
$editor = nvim
$terminal = kitty 2>/dev/null
$fileManager = dolphin
$menu = fuzzel
