# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]     = empty

# Main text color
theme[main_fg]     = "#665F2B"

# Title color for boxes
theme[title]       = "#1C120C"

# Highlight color for keyboard shortcuts
theme[hi_fg]       = "#4789A8"

# Background color of selected items
theme[selected_bg] = "#E5DCC6"

# Foreground color of selected items
theme[selected_fg] = "#1C120C"

# Color of inactive/disabled text
theme[inactive_fg] = "#665F2B"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]  = "#419C87"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]   = "#823874"

# Cpu box outline color
theme[cpu_box]     = "#9EA318"

# Memory/disks box outline color
theme[mem_box]     = "#9EA318"

# Net up/down box outline color
theme[net_box]     = "#9EA318"

# Processes box outline color
theme[proc_box]    = "#9EA318"

# Box divider line and small boxes line color
theme[div_line]    = "#9EA318"

# Temperature graph colors
theme[temp_start]  = "#9EA318"
theme[temp_mid]    = "#916D1C"
theme[temp_end]    = "#C74516"

# CPU graph colors
theme[cpu_start]   = "#9EA318"
theme[cpu_mid]     = "#916D1C"
theme[cpu_end]     = "#C74516"

# Mem/Disk free meter
theme[free_start]  = "#9EA318"
theme[free_mid]    = ""
theme[free_end]    = "#C74516"

# Mem/Disk cached meter
theme[cached_start] = "#9EA318"
theme[cached_mid]   = ""
theme[cached_end]   = "#C74516"

# Mem/Disk available meter
theme[available_start] = "#9EA318"
theme[available_mid]   = ""
theme[available_end]   = "#C74516"

# Mem/Disk used meter
theme[used_start]  = "#9EA318"
theme[used_mid]    = ""
theme[used_end]    = "#C74516"

# Download graph colors
theme[download_start] = "#9EA318"
theme[download_mid]   = "#916D1C"
theme[download_end]   = "#C74516"

# Upload graph colors
theme[upload_start] = "#9EA318"
theme[upload_mid]   = "#916D1C"
theme[upload_end]   = "#C74516"
